name = "answers-within"
compatibility_date = "2026-07-16"
workers_dev = true

routes = [
  { pattern = "answer-book.naginoumi.com", custom_domain = true }
]

[assets]
directory = "./public"
not_found_handling = "single-page-application"
